server:
  port: 10021
spring:
#配置服务链路追踪
  zipkin:
    base-url: http://127.0.0.1:9411
  application:
    name: config-service
  profiles:
    active: dev
eureka:
  instance:
    appname: 配置中心
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:10011/eureka/

