server:
  port: 1030
eureka:
  instance:
    appname: 网关
  client:
      serviceUrl:
        defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: zuul-service
zuul:
  routes:
    a:
      path: /api/**
      serviceId: fegin-service