server:
  port: 1020
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    appname: 消费中心
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: fegin-service
