#配置所有服务的注册点
eureka:
  client:
    serviceUrl:
      defaultZone:
#配置服务链路追踪
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
#缓存配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

