spring:
  application:
    name: zipkin
server:
  port: 9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10011/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false